import re

from logic.bot.executor.tools.retrieval import Retrieval
from logic.bot.executor.tools.altro import altro
from logic.bot.executor.tools.analizza import analizza
from logic.bot.executor.tools.cerca import cerca
from logic.bot.executor.tools.classifica import classifica
from logic.bot.executor.tools.confronta import confronta
from logic.bot.executor.tools.estrai_logico import estrai_logico
from logic.bot.executor.tools.estrai_semantico import estrai_semantico
from logic.bot.executor.tools.integra import integra
from logic.bot.executor.tools.riassumi import riassumi
from logic.bot.executor.tools.riformula import riformula
from logic.bot.executor.tools.riorganizza import riorganizza
from logic.bot.executor.tools.verifica import verifica

from utils.config import Config
from utils.DQL_language import DQLLanguage
from utils.file_manager import FileHandler


class Executor:
    """
    Coordinates the execution of DQL operations by integrating retrieval and LLM generation.

    This class serves as the operational engine that transforms structured tasks into
    human-readable answers. it manages document context assembly, enforces linguistic
    constraints, and handles iterative refinement if length limits are not met.

    Attributes:
        _pattern (str): Compiled regex for identifying Markdown header structures.
        FUNCTION_MAP (dict): Registry of specialized tool functions mapped to DQL commands.
    """

    # Regex for parsing Markdown headings (H1 to H6)
    _pattern = r'(?m)^\s*(#{1,6})\s*(.+)$'
    
    # Mapping table to dispatch structured commands to specific logic handlers
    FUNCTION_MAP = {
        "analizza": analizza,
        "cerca": cerca,
        "classifica": classifica,
        "confronta": confronta,
        "estrai logico": estrai_logico,
        "estrai semantico": estrai_semantico,
        "integra": integra,
        "riassumi": riassumi,
        "riformula": riformula,
        "riorganizza": riorganizza,
        "verifica": verifica
    }

    # ----------------------
    # --- Initialization ---
    # ----------------------
    
    def __init__(self, cfg: Config):
        """
        Initialize the Executor with application-wide configurations.

        Args:
            cfg (Config): Shared configuration object providing LLM access and logging.
        """
        self._cfg = cfg
        self._llm = cfg.get_LLM()
        self._logger = cfg.get_logger("Executor")
        self._language: DQLLanguage = cfg.get_DQL()

    # ----------------------
    # --- Public Methods ---
    # ----------------------
    
    def generate(self, operations: list[dict]) -> list[dict]:
        """
        Processes a sequence of planned operations to generate final results.

        This method supports both atomic operations and grouped sub-operations, 
        ensuring that intermediate results are accessible to subsequent steps 
        through the Retrieval mechanism.

        Args:
            operations (list[dict]): The execution plan generated by the Planner.

        Returns:
            list[dict]: The operations list enriched with 'result' strings for each task.
        """
        # Initialize retrieval with current operations to enable cross-task referencing
        self._retrieval = Retrieval(self._cfg, operations)
        
        for op in operations:
            self._logger.info(f"Executing operation sequence: {op['id']}")
            
            # Recursive check for nested sub-operations
            if "operations" in op:
                for o in op["operations"]:
                    self._logger.info(f"Processing sub-task: {o['id']}")
                    o["result"] = self._execute(o)
                # The primary operation result inherits from its last sub-task
                op["result"] = op["operations"][-1]["result"]
            else:
                # Direct execution for simple atomic operations
                op["result"] = self._execute(op)
            
        return operations
    
    def _execute(self, op: dict) -> str:
        """
        Internal logic for executing a single DQL operation.
        
        Orchestrates document retrieval, context building, LLM invocation, 
        limit validation, and Markdown cleanup.
        """
        structured_prompt = op.get("structured_prompt", {})
        command = structured_prompt.get("command", "altro")
        
        # 1. Gather all necessary document context
        docs = self._retrieval.execute(structured_prompt)
        context = self._build_context(docs)
        
        # 2. Extract targets and formatted linguistic constraints
        what = structured_prompt.get("what", [""])
        how = self._format_conditions(structured_prompt.get("how", {}))
        
        self._logger.info(f"Invoking tool handler for command: '{command}'")
        
        # 3. Dynamic dispatch to the appropriate tool function
        if command == "altro":
            result = altro("", context, self._cfg.get_LLM(), self._cfg.get_DQL())
        else:
            handler = self.FUNCTION_MAP.get(command)
            result = handler(context, what, how, self._cfg.get_LLM(), self._cfg.get_DQL())
        
        # 4. Limit enforcement loop: iterative re-generation if constraints are violated
        if "limit" in structured_prompt.get("how", {}):
            attempt = 0
            limit_cfg = structured_prompt["how"]["limit"]
            
            # Allow up to 3 rephrasing attempts to satisfy the requested length/count
            while (not self.check_limit(result, context, limit_cfg)) and (attempt < 3):
                self._logger.info(f"Limit violation detected. Retrying with 'riformula' (Attempt {attempt+1})")
                
                # Feedback loop: provide previous answer to the LLM for adjustment
                new_context = f"[RISPOSTA PRECEDENTEMENTE GENERATA]\n\n{result}\n\n---{context}"
                result = self.FUNCTION_MAP.get("riformula")(new_context, what, how, self._cfg.get_LLM(), self._cfg.get_DQL())
                attempt += 1
                
            if attempt < 3 or self.check_limit(result, context, limit_cfg):
                self._logger.info("Content limit successfully satisfied.")

        # 5. Post-processing: transform Markdown headers into formatted Bold/Italic
        return re.sub(self._pattern, self._format_heading, result)

    # ----------------------
    # --- Input Context  ---
    # ----------------------
    
    def _format_conditions(self, how: dict) -> str:
        """
        Serializes 'how' constraints into natural language instructions for the LLM.

        Args:
            how (dict): Dictionary of extracted constraints (e.g., limit, language).

        Returns:
            str: A formatted string block to be appended to the prompt.
        """
        if not how:
            return ""

        # Block introduction
        conditions = ["Tuttavia, l'utente ha posto esplicitamente che la risposta debba soddisfare le seguenti condizioni:"]
        
        for key, value in how.items():
            if value:
                if key == "limit":
                    # Specialized formatting for numerical constraints (words, characters, paragraphs)
                    sign = value['sign']
                    if sign == "*":
                        sign = f"tale per cui il prodotto con il numero di {value['unit']} sia pari a"
                        
                    conditions.append(f"- È obbligatorio che la risposta abbia un numero di {value['unit']} {sign} {value['number']}")
                else:
                    # General descriptive conditions
                    conditions.append(f"- Condizione \"{key}\": {value}")

        return "\n".join(conditions) if len(conditions) > 1 else ""

    @staticmethod
    def _build_context(docs: list[dict]) -> str:
        """
        Concatenates multiple retrieved documents into a labeled context block.

        Args:
            docs (list[dict]): List of documents with 'type' and 'text'.

        Returns:
            str: Structured text block for RAG (Retrieval-Augmented Generation).
        """
        if not docs:
            return ""
        
        context_lines = []
        for doc in docs:
            # Labeled headers help the LLM distinguish between different source materials
            context_lines.append(f"[D. \"{doc['type']}\"]\n\n{doc['text']}\n\n---")
        
        context_str = "\n\n".join(context_lines).strip()
        return f"Context:\n{context_str}"
    
    # -------------------------
    # --- Output Formatting ---
    # -------------------------

    @staticmethod
    def _format_heading(match: re.Match) -> str:
        """
        Custom formatter for Markdown headings.
        Converts # symbols into UI-friendly Bold/Underline styles.
        """
        level = len(match.group(1))
        content = match.group(2).strip()
        
        # Heuristic mapping for Streamlit/UI rendering
        if level == 1:
            return f"**{content}**"  # Bold for main title
        elif level == 2:
            return f"__{content}__"  # Underline for section
        elif level == 3:
            return f"*{content}*"    # Italic for subsection
        
        return content 
    
    # -----------------------------
    # --- Check Limit Condition ---
    # -----------------------------
    
    def check_limit(self, text: str, context: str, constraint: dict) -> bool:
        """
        Validates the generated output against numerical constraints.

        Args:
            text (str): The newly generated response text.
            context (str): The input context (for relative '*' limits).
            constraint (dict): The limit parameters (number, sign, unit).

        Returns:
            bool: True if the text complies with the constraint (including tolerance).
        """
        file_handler = FileHandler()
        
        sign = constraint.get("sign", "")
        number = constraint.get("number", "")
        unit = constraint.get("unit", "")

        # Immediate bypass if no constraint is defined
        if sign == "" or number == "":
            return True

        # Perform lexical analysis to count units (words, chars, etc.)
        current_value = file_handler.text_analysis(text, unit)
        
        if sign == "*":
            # Relative limit calculation (e.g., "half the length of the original")
            context_value = file_handler.text_analysis(context, unit)
            target_number = number * context_value
            
            # Apply a 15% fuzzy logic tolerance for natural language variation
            tolerance = target_number * 0.15
            self._logger.info(f"Relative Limit Check: {current_value} units found (Target: {target_number} ±{tolerance})")
            return (target_number - tolerance) <= current_value <= (target_number + tolerance)
        
        self._logger.info(f"Absolute Limit Check: {current_value} {sign} {number}")

        # Basic comparison operators
        if sign == "=":
            return current_value == number
        elif sign == "<=":
            return current_value <= number
        elif sign == ">=":
            return current_value >= number
        elif sign == "~":
            # Approximation check with 15% tolerance
            tolerance = number * 0.15
            return (number - tolerance) <= current_value <= (number + tolerance)
        
        raise ValueError(f"Constraint operator not supported: {sign}")