import re

from logic.bot.executor.tools.retrieval import Retrieval
from logic.bot.executor.tools.analizza import analizza
from logic.bot.executor.tools.cerca import cerca
from logic.bot.executor.tools.classifica import classifica
from logic.bot.executor.tools.confronta import confronta
from logic.bot.executor.tools.estrai_logico import estrai_logico
from logic.bot.executor.tools.estrai_semantico import estrai_semantico
from logic.bot.executor.tools.integra import integra
from logic.bot.executor.tools.riassumi import riassumi
from logic.bot.executor.tools.riorganizza import riorganizza
from logic.bot.executor.tools.verifica import verifica

from utils.config import Config
from utils.DQL_language import DQLLanguage
from utils.file_manager import FileHandler


class Executor:
    """
    Coordinates the execution of DQL operations by integrating retrieval and LLM generation.

    This class serves as the operational engine that transforms structured tasks into
    human-readable answers. it manages document context assembly, enforces linguistic
    constraints, and handles iterative refinement if length limits are not met.

    Attributes:
        _pattern (str): Compiled regex for identifying Markdown header structures.
        FUNCTION_MAP (dict): Registry of specialized tool functions mapped to DQL commands.
    """

    # Regex for parsing Markdown headings (H1 to H6)
    _pattern = r'(?m)^\s*(#{1,6})\s*(.+)$'
    
    # Mapping table to dispatch structured commands to specific logic handlers
    FUNCTION_MAP = {
        "analizza": analizza,
        "cerca": cerca,
        "classifica": classifica,
        "confronta": confronta,
        "estrai logico": estrai_logico,
        "estrai semantico": estrai_semantico,
        "integra": integra,
        "riassumi": riassumi,
        "riorganizza": riorganizza,
        "verifica": verifica
    }
    
    TOLERANCE = 0.20

    # ----------------------
    # --- Initialization ---
    # ----------------------
    
    def __init__(self, cfg: Config):
        """
        Initialize the Executor with application-wide configurations.

        Args:
            cfg (Config): Shared configuration object providing LLM access and logging.
        """
        self._cfg = cfg
        self._llm = cfg.get_LLM()
        self._logger = cfg.get_logger("Executor")
        self._language: DQLLanguage = cfg.get_DQL()
        self.file_handler = FileHandler()

    # ----------------------
    # --- Public Methods ---
    # ----------------------
    
    def generate(self, operations: list[dict]) -> list[dict]:
        """
        Processes a sequence of planned operations to generate final results.

        This method supports both atomic operations and grouped sub-operations, 
        ensuring that intermediate results are accessible to subsequent steps 
        through the Retrieval mechanism.

        Args:
            operations (list[dict]): The execution plan generated by the Planner.

        Returns:
            list[dict]: The operations list enriched with 'result' strings for each task.
        """
        # Initialize retrieval with current operations to enable cross-task referencing
        self._retrieval = Retrieval(self._cfg, operations)
        
        for op in operations:
            self._logger.info(f"Executing operation sequence: {op['id']}")
            
            # Recursive check for nested sub-operations
            if "operations" in op:
                for o in op["operations"]:
                    self._logger.info(f"Processing sub-task: {o['id']}")
                    o["result"] = self._execute(o)
                # The primary operation result inherits from its last sub-task
                op["result"] = op["operations"][-1]["result"]
            else:
                # Direct execution for simple atomic operations
                op["result"] = self._execute(op)
            
        return operations
    
    def _execute(self, op: dict) -> str:
        """
        Internal logic for executing a single DQL operation.
        
        Orchestrates document retrieval, context building, LLM invocation, 
        limit validation, and Markdown cleanup.
        """
        structured_prompt = op.get("structured_prompt", {})
        command = structured_prompt.get("command", "altro")
        
        # 1. Gather all necessary document context
        docs = self._retrieval.execute(structured_prompt)
        
        if "limit" in structured_prompt.get("how", {}):
            structured_prompt.get("how", {})["limit"] = self._disamgiguate_percent_limit(structured_prompt.get("how", {}).get("limit", {}), str(docs))

        self._logger.info(f"Invoking tool handler for command: '{command}'")
        
        # 3. Dynamic dispatch to the appropriate tool function
        try:
            result = self.FUNCTION_MAP.get(command, None)(
                docs,
                structured_prompt,
                self._llm,
                self._language
            )
        except Exception as e:
            self._logger.error(f"Error during execution of command '{command}': {str(e)}")
            raise ValueError(f"Execution failed for command '{command}': {str(e)}")

        # 4. Post-processing finale
        return result
        
        #return re.sub(self._pattern, self._format_heading, result)
    
    
    def _disamgiguate_percent_limit(self, limit_cfg: dict, context: str) -> dict:
        """
        Converts percentage-based limits into absolute numerical values.

        Args:
            limit_cfg (dict): The original limit configuration with '%' sign.
            context (str): The text context to base the calculation on.
        Returns:
            dict: Updated limit configuration with absolute number.
        """
        if limit_cfg.get("sign", "") != "%":
            return limit_cfg
        
        number = limit_cfg.get("number", 0)
        unit = limit_cfg.get("unit", "parole")
        
        context_value = self.file_handler.text_analysis(context, unit)
        
        absolute_number = (number / 100) * context_value
        new_sign = "<=" if number <= 100 else ">="
        
        return {
            "sign": new_sign,
            "number": round(absolute_number),
            "unit": unit
        }
    
    # -------------------------
    # --- Output Formatting ---
    # -------------------------

    @staticmethod
    def _format_heading(match: re.Match) -> str:
        """
        Custom formatter for Markdown headings.
        Converts # symbols into UI-friendly Bold/Underline styles.
        """
        level = len(match.group(1))
        content = match.group(2).strip()
        
        # Heuristic mapping for Streamlit/UI rendering
        if level == 1:
            return f"**{content}**"  # Bold for main title
        elif level == 2:
            return f"__{content}__"  # Underline for section
        elif level == 3:
            return f"*{content}*"    # Italic for subsection
        
        return content 