from typing import List, Dict, Any

from utils.config import Config
from utils.DQL_language import DQLLanguage

class Planner:
    """
    Decomposes high-level DQL commands into executable atomic operations.

    This class analyzes the structured query to determine if a multi-step 
    execution plan is required (e.g., extracting data before summarizing it). 
    It ensures that each step is tailored to specific data sources and 
    logical dependencies.

    Responsibilities:
        - Orchestrating the transformation from high-level intent to atomic steps.
        - Resolving intermediate commands based on the 'what' parameter context.
        - Managing data integration across multiple sources.
        - Avoiding command conflicts (e.g., search vs. extraction).
    """

    def __init__(self, cfg: Config):
        """
        Initialize the Planner with language definitions and logging.

        Args:
            cfg (Config): Global configuration providing access to DQL language grammar.
        """
        self._logger = cfg.get_logger("Planner")
        self._project_root = cfg.project_root
        self._dql_language: DQLLanguage = cfg.get_DQL()
        
        # Cache of valid source names to identify which 'from' items require retrieval
        self._sources_name = [
            src.get("name", "") for src in self._dql_language.get_sources()
        ]

    # -------------------------------------------------------------------------
    # Public Methods
    # -------------------------------------------------------------------------

    def decompose(self, operations: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Analyzes and flattens a list of high-level operations into a detailed execution plan.

        Args:
            operations (list[dict]): A list of structured queries generated by the Translator.

        Returns:
            list[dict]: A plan where complex operations are replaced or enriched with 
                       sub-operation sequences.
        """
        final_plan = []

        for op in operations:
            # Generate sub-steps for the current operation
            decomposed_ops = self._process_operation(op)
            
            # If no expansion occurred, append the single operation
            if len(decomposed_ops) == 1:
                decomposed_ops[0]["id"] = op["id"]
                decomposed_ops[0]["prompt"] = op["prompt"]
                final_plan.append(decomposed_ops[0])
            else:
                # Group sub-operations within the original operation structure
                op['operations'] = decomposed_ops
                final_plan.append(op)

        return final_plan

    # -------------------------------------------------------------------------
    # Private Decomposition Logic
    # -------------------------------------------------------------------------

    def _process_operation(self, op: Dict[str, Any]) -> List[Dict[str, Any]]:
        """
        Main routing logic for a single operation decomposition.
        Iterates over 'what' elements to build specific retrieval/analysis steps.
        """
        op_id = op.get("id", "unknown")
        prompt = op.get("structured_prompt", {})
        
        self._logger.info(f"Decomposing operation ID: {op_id}")

        command = prompt.get("command", "altro")
        sources = prompt.get("from", [])
        whats = prompt.get("what", ["altro"])
        how = prompt.get("how", {})

        # 'altro' command bypasses decomposition
        if command == "altro":
            return [op]

        sub_operations = []
        last_step_ids = []

        # Each 'what' element represents a target entity or section to process
        for what_item in whats:
            start_idx = len(sub_operations)
            processed_steps = self._process_what_element(
                command, sources, what_item, how, op_id, start_idx
            )
            sub_operations.extend(processed_steps)
            
            # Track the final ID of each 'what' branch for potential integration
            if processed_steps:
                last_step_ids.append(processed_steps[-1].get("id"))

        # Finalize by adding an integration step if multiple branches were created
        return self._finalize_integration(sub_operations, last_step_ids, op_id)

    def _process_what_element(self, command: str, sources: list, what: str, 
                             how: dict, parent_id: str, start_idx: int) -> List[Dict]:
        """
        Determines the strategy for a single 'what' element based on command type 
        and source availability.
        """
        # Identify which intermediate commands (e.g., search, extract) support this 'what'
        middle_commands = self._find_middle_commands(what)
        
        # Case A: User requested an intermediate command directly
        if command in middle_commands:
            if len(sources) > 1:
                # Multi-source intermediate commands require per-source steps + integration
                self._logger.info(f"Decomposing '{command}' over multiple sources.")
                return self._create_operations(command, "integra", sources, what, how, parent_id, start_idx)
            
            return [self._build_step(parent_id, start_idx, command, sources, [what], how)]

        # Case B: Final command (e.g., 'summarize') that requires a preceding data fetch
        if self._need_decomposition(command, sources, what):
            self._logger.info(f"Decomposing final command '{command}' using {middle_commands[0]}")
            
            if command == "riassumi":
                return self._decompose_summarize(middle_commands[0], sources, what, how, parent_id, start_idx)
            
            # Standard two-step plan: mid_cmd (retrieval) -> final_cmd (analysis/integration)
            return self._create_operations(middle_commands[0], command, sources, what, how, parent_id, start_idx)

        # Case C: Direct execution on the full document or unknown source
        return [self._build_step(parent_id, start_idx, command, sources, [what], how)]

    # -------------------------------------------------------------------------
    # Operation Builders
    # -------------------------------------------------------------------------

    def _create_operations(self, mid_cmd: str, final_cmd: str, sources: list, 
                          what: str, how: dict, p_id: str, start_idx: int) -> List[Dict]:
        """
        Builds a sequence of per-source retrieval steps followed by an aggregation step.
        """
        # Logic to prevent redundant searching vs extraction
        if (mid_cmd == "cerca" and "estrai" in final_cmd) or ("estrai" in mid_cmd and "cerca" == final_cmd):
            self._logger.warning("Conflict between 'cerca' and 'estrai' detected.")
            if len(sources) == 1:
                return [self._build_step(p_id, start_idx, mid_cmd, sources, [what], how)]
            return self._create_operations(mid_cmd, "integra", sources, what, how, p_id, start_idx)

        atomic_ops = []
        not_used_sources = []

        # Create individual retrieval steps for known database sources
        if what != "intero documento":
            for i, src in enumerate(sources, start=start_idx):
                if src in self._sources_name:
                    atomic_ops.append(self._build_step(p_id, i, mid_cmd, [src], [what]))
                else:
                    # Items from previous steps (strings/IDs) are collected for the final step
                    not_used_sources.append(src)
        else:
            not_used_sources = sources
        
        final_op = []
        if len(atomic_ops) == 1 and len(not_used_sources) == 0:
            atomic_ops[-1]["structured_prompt"]["how"] = how
        else:
            # Final aggregation step links back to the IDs of the atomic operations
            final_step_id = f"{p_id}_{len(atomic_ops) + start_idx}"
            final_op = [
                {
                    "id": final_step_id,
                    "structured_prompt": {
                        "command": final_cmd,
                        "from": [op["id"] for op in atomic_ops] + not_used_sources,
                        "how": how
                    }
                }
            ]
        
        return atomic_ops + final_op

    def _decompose_summarize(self, mid_cmd: str, sources: list, what: str, 
                            how: dict, p_id: str, start_idx: int) -> List[Dict]:
        """
        Specialized pipeline for 'summarize': Retrieve data -> Integrate -> Summarize.
        """
        # Optimize: if only one source exists and not any particular what, middle ops are useless
        if what == "intero documento" and len(sources) == 1:
            ops = []
            op_id = sources[0]
        else:
            # Generate retrieval and integration steps
            ops = self._create_operations(mid_cmd, "integra", sources, what, {}, p_id, start_idx)
            
            # Optimize: if only one source exists, 'integra' is redundant
            if len(ops) == 2:
                ops.pop(-1)
            
            op_id = ops[-1]["id"]

        # Append the final summarization command referencing the previous results
        summarize_step = self._build_step(
            p_id, start_idx + len(ops), "riassumi", [op_id], how=how
        )
        ops.append(summarize_step)
        return ops

    def _finalize_integration(self, ops: List[Dict], last_ids: List[str], p_id: str) -> List[Dict]:
        """
        Appends a global 'integra' step if the plan resulted in multiple terminal outputs.
        """
        if len(last_ids) > 1:
            integration_step = {
                "id": f"{p_id}_{len(ops)}",
                "structured_prompt": {
                    "command": "integra",
                    "from": last_ids
                }
            }
            ops.append(integration_step)
        return ops

    # -------------------------------------------------------------------------
    # Helpers
    # -------------------------------------------------------------------------

    def _build_step(self, p_id: str, idx: int, cmd: str, src: list, 
                   what: list = None, how: dict = None) -> Dict:
        """
        Factory method for standard operation dictionaries.
        """
        prompt = {"command": cmd, "from": src}
        if what: prompt["what"] = what
        if how: prompt["how"] = how
        return {"id": f"{p_id}_{idx}", "structured_prompt": prompt}

    def _find_middle_commands(self, what: str) -> List[str]:
        """
        Consults the DQL language grammar to find appropriate intermediate commands for a 'what'.
        """
        if what in ["intero documento", "altro"]:
            return ["cerca"]
        
        # Search the 'what' definitions for related command mappings
        for item in self._dql_language.get_what():
            if what == item.get("name", ""):
                relative = item.get("relative_command", [])
                if relative:
                    return relative
                break
        
        # Fallback to the system default command (usually 'cerca')
        default = self._dql_language.default_command.get("command", "cerca")
        return [default]

    def _need_decomposition(self, command, sources: list, what: str) -> bool:
        """
        Heuristic to determine if a query requires multi-step decomposition.
        """
        has_dql_source = any(s in self._sources_name for s in sources)
        command_special_case = (command == "confronta") and (len(sources) == 1)
        return has_dql_source or what != "intero documento" or command_special_case