import os
from spellchecker import SpellChecker
from utils.config import Config


class SpellingChecker:
    """
    Provides text correction capabilities using both a traditional spell checker
    and an LLM-based rewriting system for advanced grammar and phrasing correction.

    Responsibilities:
        - Detect and correct spelling errors using a rule-based spell checker.
        - Optionally refine text using a language model prompt for contextual rewriting.

    Attributes:
        llm (LLM): Reference to the application's language model (from Config).
        project_root (Path): Root path of the project, used to locate prompt templates.
        spell (SpellChecker): Instance of the pyspellchecker library configured for Italian.
        logger: Logger instance from Config.
        spell_check_without_llm (bool): Flag which method we wanna use.
    """
    
    # ----------------------
    # --- Initialization ---
    # ----------------------

    def __init__(self, cfg: Config):
        """
        Initialize the SpellingChecker with configuration and resources.

        Args:
            cfg (Config): The global configuration object providing access to
                          the LLM instance and project paths.
        """
        self.llm = cfg.llm
        self.project_root = cfg.project_root
        self.spell = SpellChecker(language="it")
        
        self.logger = cfg.get_logger("Spelling Checker")
        self.spell_check_without_llm = cfg.spell_check_without_llm
        
    # ------------------------
    # --- General Function ---
    # ------------------------
    
    def correct_spelling(self, text: str) -> str:
        if self.spell_check_without_llm:
            self.logger.info(f"Spelling Correction with pyspellchecker")
            corrected_query = self._correct_text(text)
        else:
            self.logger.info(f"Spelling Correction with LLM")
            corrected_query = self._correct_text_llm(text)
        
        # Log the final query for traceability
        self.logger.info(f"Spelling Correction: {corrected_query}")
        return corrected_query
        
    # ----------------------------
    # --- Basic Spell Checking ---
    # ----------------------------
    
    def _correct_text(self, text: str) -> str:
        """
        Perform a basic spell correction on the provided text using the pyspellchecker.

        Args:
            text (str): Input text to correct.

        Returns:
            str: Corrected text with spelling errors fixed.
        """
        if not text or not isinstance(text, str):
            return ""

        # Tokenize and lowercase words for consistency
        words = text.lower().split()

        # Correct each word individually
        corrected_words = [self.spell.correction(word) for word in words]

        # Reassemble the corrected sentence
        return " ".join(filter(None, corrected_words))

    # ----------------------------
    # --- LLM-Based Correction ---
    # ----------------------------
    
    def _correct_text_llm(self, text: str) -> str:
        """
        Perform advanced text correction using the configured LLM model.

        This method leverages a prompt template (JSON) that guides the LLM
        to rewrite the input text with improved spelling and grammar.

        Args:
            text (str): Input text to correct contextually.

        Returns:
            str: Corrected or rewritten text generated by the LLM.
        """
        if not text or not isinstance(text, str):
            return ""

        prompt_path = os.path.join(
            self.project_root,
            "documents",
            "prompts",
            "rewriting",
            "1 - CorrectionQuery.json",
        )

        return self.llm.invoke(prompt_path, {"query": text})
